version: '3'
services:
  search-app:
    image: akshayverma004/search-app
    ports:
      - "81:80"
    deploy:
      replicas: 2
    volumes:
      - var/lib/search-app
  
  payment-app:
   image: akshayverma004/payment-app
   ports:
     - "82:80"
   deploy: 
       replicas: 2
   volumes:
      - var/lib/payment-app

  cart-app:
    image: akshayverma004/cart-app
    ports:
      - "83:80"
    deploy:
      replicas: 2
    volumes:
      - /var/lib/cart-app