version: '3'

services:
  search-app:
    image: akshayverma004/search-img:v1.0
    ports:
      - "81:80"
    deploy:
      replicas: 3
  
  payment-app:
   image: akshayverma004/payment-img:v1.0
   ports:
     - "82:80"
   deploy: 
      replicas: 3

  cart-app:
    image: akshayverma004/cart-img:v1.0
    ports:
      - "83:80"
    deploy:
      replicas: 3
